name: Provision AWS Resources

on:
  workflow_dispatch:
  push:
    branches: [master]
    paths: ["backend/terraform/**"]

  pull_request:
    branches: [master]
    paths: ["backend/terraform/**"]

jobs:
  plan:
    name: Terraform plan
    runs-on: ubuntu-latest
    env:
      TF_VAR_open_api_key: ${{ secrets.OPEN_API_KEY }}
      TF_VAR_chroma_api_key: ${{ secrets.CHROMADB_API_KEY }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Terraform init
        run: |
          cd backend/terraform
          terraform init

      - name: Terraform plan
        run: |
          cd backend/terraform
          terraform plan -out=tfplan

      - name: Upload plan artifact
        uses: actions/upload-artifact@v4
        with:
          name: tf-artifacts
          path: |
            backend/terraform/tfplan

  deploy:
    name: Terraform Deploy
    needs: plan
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    env:
      TF_VAR_open_api_key: ${{ secrets.OPEN_API_KEY }}
      TF_VAR_chroma_api_key: ${{ secrets.CHROMADB_API_KEY }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Download plan artifact
        uses: actions/download-artifact@v5
        with:
          name: tf-artifacts
          path: backend/terraform

      - name: Terraform init
        run: |
          cd backend/terraform
          terraform init

      - name: Terraform apply
        run: |
          cd backend/terraform
          terraform apply tfplan
